### PR TITLE
Update bluetooth.py

### PR DESCRIPTION
**Pull request by gregg00**
Add alias Y7S , alias of older pinetime.

I am able to successfully connect to my pinetime after adding the Y7S alias

### CODE REVIEW

**Comment by gregg00** [comment]
I am able to connect to the pinetime, but am getting an error when trying to flash firmware, 1.0.0 from siglo instructions on pinetime wiki.  
Error : dbus.connection :Exception in handler or D-Bus signal: 
Traceback (most recent call last): 
File "/usr/lib/python3.9/site-packages/dbus/connection.py", line 232, in maybe_handle_message
self._handler(*args, **kwargs)
File "/usr/lib/python3.9/site-packages/gatt/gatt_linux.py", line 379, in properties_changed
self.services_resolved()
FIle "/usr/local/share/siglo/siglo/ble_dfu.py", line 172, in services_resolved
ble_dfu_serv = next(s for s in self.services if s.uuid == self.UUID_DFU_SERVICE)
StopIteration

**Comment by alex-startengine** [comment]
ok so this is not ready for merge yet? I had to change computers for work so haven't been able to develop on linux lately.

**Comment by gregg00** [comment]
Ready for merge.  
I followed what you did in this [commit](https://github.com/alexr4535/siglo/commit/97977260b0176b8a984021c17c825357336abc41) , and added Y7S to the list of aliases.  My pinephone can now find my pinetime.

I think not being able to flash is a different issue.  

Sorry and thanks.  - Greg

**Comment by alexr4535** [comment]
ty!

**Pull request merged**
